# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
locale          : "en-US"
title           : "Another Wikipedia Viewer"
name            : "Muhamad Fakhrusy"
description     : "I Build Things on The Web" # this means to ignore newlines until "baseurl:"
skills          : "Front End Developer - Back End Developer"

baseurl         : "/wikipedia-viewer" # the subpath of your site, e.g. /blog
url             : "https://mfakhrusy.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Site Author
author:
  name          : "Muhamad Fakhrusy"
  nickname      : "mfakhrusy"
  bio           :
  location      :
  email         : "fakhrusy.m@gmail.com"
  github        : "mfakhrusy"
  gitlab        : 
  codepen       : 
  instagram     : 
  twitter       : "v8areu"
  facebook      :
  linkedin      : "mfakhrusy"
  stackoverflow :
  youtube       :

# Build settings
markdown        : kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - node_modules
  - package.json
  - gulpfile.js